# Generated by Django 5.2.1 on 2025-06-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("rollno", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=30)),
                ("address", models.CharField(max_length=30)),
            ],
        ),
    ]
