# Generated by Django 5.2.1 on 2025-06-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SampleApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="rollno",
            new_name="rollnum",
        ),
    ]
