# Generated by Django 5.2.1 on 2025-06-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SampleApp", "0002_rename_rollno_student_rollnum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="rollnum",
            new_name="rollno",
        ),
    ]
